#pragma once

// This component provides a struct, `TracerConfig`, used to configure a
// `Tracer`.  `Tracer` is instantiated with a `FinalizedTracerConfig`, which
// must be obtained from the result of a call to `finalize_config`.

#include <chrono>
#include <cstddef>
#include <memory>
#include <variant>
#include <vector>

#include "clock.h"
#include "datadog/event_scheduler.h"
#include "datadog/http_client.h"
#include "datadog/tracer_telemetry.h"
#include "datadog_agent_config.h"
#include "error.h"
#include "expected.h"
#include "propagation_style.h"
#include "runtime_id.h"
#include "span_defaults.h"
#include "span_sampler_config.h"
#include "trace_sampler_config.h"

namespace datadog {
namespace tracing {

class Collector;
class Logger;
class SpanSampler;
class TraceSampler;

// `FinalizedTracerConfig` contains `Tracer` implementation details derived from
// a valid `TracerConfig` and accompanying environment.
// `FinalizedTracerConfig` must be obtained by calling `finalize_config`.
class FinalizedTracerConfig {
  friend class TracerConfig;
  FinalizedTracerConfig() = default;

 public:
  SpanDefaults defaults;

  std::shared_ptr<Collector> collector;

  FinalizedDatadogAgentConfig agent_config;
  FinalizedTraceSamplerConfig trace_sampler;
  FinalizedSpanSamplerConfig span_sampler;

  std::vector<PropagationStyle> injection_styles;
  std::vector<PropagationStyle> extraction_styles;

  bool report_traces;
  bool report_hostname;
  std::size_t tags_header_size;
  std::shared_ptr<Logger> logger;
  bool log_on_startup;
  bool trace_id_128_bit;
  bool report_telemetry;
  Optional<RuntimeID> runtime_id;
  Clock clock;

  std::vector<ConfigTelemetry> telemetry_data;
};

class TracerConfig {
 public:
  TracerConfig();

  // clang-format off

  // Set the application name.
  //
  // Overriden by the `DD_SERVICE` environment variables.
  TracerConfig& set_service_name(std::string service_name, ConfigOrigin origin = ConfigOrigin::CODE);

  // All the rest are optional and can be most of the time overridden by
  // environment variables.
  TracerConfig& set_service_type(std::string service_type, ConfigOrigin origin = ConfigOrigin::CODE);

  // Set the application environment.
  //
  // Overriden by the `DD_ENV` environment variable.
  // Example: `prod`, `pre-prod` or `staging`.
  TracerConfig& set_environment(std::string environment, ConfigOrigin origin = ConfigOrigin::CODE);

  // Set the application version.
  //
  // Overriden by the `DD_VERSION` environment variable.
  // Exemple values: `1.2.3`, `6c44da20`, `2020.02.13`.
  TracerConfig& set_version(std::string version, ConfigOrigin origin = ConfigOrigin::CODE);

  // Set the default name for spans.
  TracerConfig& set_span_default_name(std::string name, ConfigOrigin origin = ConfigOrigin::CODE);

  // Set global tags to be attached to every span.
  //
  // Overriden by the `DD_TAGS` environment variable.
  TracerConfig& set_tags(std::unordered_map<std::string, std::string> tags, ConfigOrigin origin = ConfigOrigin::CODE);

  // A URL at which the Datadog Agent can be contacted.
  // The following formats are supported:
  //
  // - http://<domain or IP>:<port>
  // - http://<domain or IP>
  // - http+unix://<path to socket>
  // - unix://<path to socket>
  //
  // The port defaults to 8126 if it is not specified.
  //
  // Overriden by the `DD_TRACE_AGENT_URL` environment variable.
  TracerConfig& set_datadog_agent_url(std::string url, ConfigOrigin origin = ConfigOrigin::CODE);

  // Indicates whether traces generated by the tracer will be
  // sent to a collector (`true`) or discarded on completion (`false`).
  // If `report_traces` is `false`, then both `agent` and `collector` are ignored.
  //
  // Overridden by the `DD_TRACE_ENABLED` environment variable.
  TracerConfig& enable_traces(bool report_traces, ConfigOrigin origin = ConfigOrigin::CODE);

  // Indicates whether telemetry about the tracer will be send to a collector
  // a collector (`true`) or discarded on completion (`false`).  
  // If `report_telemetry` is `false`, then this feature is disabled.
  //
  // Overridden by the `DD_INSTRUMENTATION_TELEMETRY_ENABLED` environment variable.
  TracerConfig& enable_telemetry(bool report_telemetry, ConfigOrigin origin = ConfigOrigin::CODE);

  // Indicates whether the tracer will generate 128-bit trace IDs.
  // If `true`, the tracer will generate 128-bit trace IDs. If false, the
  // tracer will generate 64-bit trace IDs.
  //
  // Overriden by the `DD_TRACE_128_BIT_TRACEID_GENERATION_ENABLED` environment variable.
  TracerConfig& enable_128bit_trace_id(bool report_128bit_trace_id, ConfigOrigin origin = ConfigOrigin::CODE);

  // `log_on_startup` indicates whether the tracer will log a banner of
  // configuration information once initialized.
  //
  // Overridden by the `DD_TRACE_STARTUP_LOGS` environment variable.
  TracerConfig& log_configuration_on_startup(bool log_on_startup, ConfigOrigin origin = ConfigOrigin::CODE);

  // Indicates with which tracing systems trace propagation
  // will be compatible when injecting (sending) trace context.
  // All styles indicated by `injection_styles` are used for injection.
  //
  // Overridden by the `DD_TRACE_PROPAGATION_STYLE_INJECT` 
  // and `DD_TRACE_PROPAGATION_STYLE` environment variables.
  TracerConfig& set_injection_styles(std::vector<PropagationStyle> injeciton_styles, ConfigOrigin origin = ConfigOrigin::CODE);

  // Indicates with which tracing systems trace propagation
  // will be compatible when extracting (receiving) trace context.
  // Extraction styles are applied in the order in which they appear in
  // `extraction_styles`. The first style that produces trace context or
  // produces an error determines the result of extraction.
  //
  // Overridden by the `DD_TRACE_PROPAGATION_STYLE_EXTRACT` and `DD_TRACE_PROPAGATION_STYLE`
  // environment variables.
  TracerConfig& set_extraction_styles(std::vector<PropagationStyle> extraction_styles, ConfigOrigin origin = ConfigOrigin::CODE);

  // `trace_sampler` configures trace sampling. Trace sampling determines which
  // traces are sent to Datadog.  See `trace_sampler_config.h`.
  //
  // Overriden by `DD_TRACE_SAMPLING_RULES`, `DD_TRACE_SAMPLE_RATE`
  // and `DD_TRACE_RATE_LIMIT` environment variables.
  TracerConfig& set_trace_sampler(TraceSamplerConfig trace_sampler, ConfigOrigin origin = ConfigOrigin::CODE);

  // `span_sampler` configures span sampling.  Span sampling allows specified
  // spans to be sent to Datadog even when their enclosing trace is dropped by
  // the trace sampler.  See `span_sampler_config.h`.
  //
  // Overriden by `DD_SPAN_SAMPLING_RULES` and `DD_SPAN_SAMPLING_RULES_FILE`
  // environment variables.
  TracerConfig& set_span_sampler(SpanSamplerConfig trace_sampler, ConfigOrigin origin = ConfigOrigin::CODE);

  // `report_hostname` indicates whether the tracer will include the result of
  // `gethostname` with traces sent to the collector.
  TracerConfig& enable_hostname_in_span(bool report_hostname, ConfigOrigin origin = ConfigOrigin::CODE);

  // The `HTTPClient` used to submit traces to the Datadog Agent.  If this
  // library was built with libcurl (the default), then `http_client` is
  // optional: a `Curl` instance will be used if `http_client` is left null.
  // If this library was built without libcurl, then `http_client` is required
  // not to be null.
  TracerConfig& set_http_client(std::shared_ptr<HTTPClient> http_client, ConfigOrigin origin = ConfigOrigin::CODE);

  // The `EventScheduler` used to schedule recurring task like periodically 
  // submit batches of traces to the `Collector`.
  // If `event_scheduler` is null, then a `ThreadedEventScheduler` instance will
  // be used instead.
  TracerConfig& set_event_scheduler(std::shared_ptr<EventScheduler> event_scheduler, ConfigOrigin origin = ConfigOrigin::CODE);

  // `flush_interval` denotes the duration, in milliseconds, between batches of traces
  // being sent to the `Collector`.
  TracerConfig& set_flush_interval(std::chrono::milliseconds flush_interval, ConfigOrigin origin = ConfigOrigin::CODE);

  // `request_timeout` denotes the maximum duration, in milliseconds, an HTTP
  // request is allowed to run.
  TracerConfig& set_request_timeout(std::chrono::milliseconds request_timeout, ConfigOrigin origin = ConfigOrigin::CODE);

  // `shutdown_timeout` denotes the maximum duration, in milliseconds, the tracer
  // allows work in progress before shutting down.
  TracerConfig& set_shutdown_timeout(std::chrono::milliseconds shutdown_timeout, ConfigOrigin origin = ConfigOrigin::CODE);

  // A `Collector` instance that the tracer will use to report traces.
  // If `collector` is null, then a `DatadogAgent` instance will be created.
  // Note that `collector` is ignored if `report_traces` is `false`.
  TracerConfig& set_collector(std::shared_ptr<Collector> collector, ConfigOrigin origin = ConfigOrigin::CODE);

  // `max_tags_header_size` is the maximum allowed size, in bytes, of the serialized
  // value of the "X-Datadog-Tags" header used when injecting trace context for
  // propagation.  If the serialized value of the header would exceed
  // `tags_header_size`, the header will be omitted instead.
  TracerConfig& set_max_tags_header_size(std::size_t max_tags_header_size, ConfigOrigin origin = ConfigOrigin::CODE);

  // `logger` specifies how the tracer will issue diagnostic messages. If
  // `logger` is null, then it defaults to a logger that inserts into
  // `std::cerr`.
  TracerConfig& set_logger(std::shared_ptr<Logger> logger, ConfigOrigin origin = ConfigOrigin::CODE);

  // `runtime_id` denotes the current run of the application in which the tracer
  // is embedded. If `runtime_id` is not specified, then it defaults to a
  // pseudo-randomly generated value. A server that contains multiple tracers,
  // such as those in the worker threads/processes of a reverse proxy, might
  // specify the same `runtime_id` for all tracer instances in the same run.
  TracerConfig& set_runtime_id(RuntimeID runtime_id, ConfigOrigin origin = ConfigOrigin::CODE);

  // Set how often, in seconds, to query the Datadog Agent for remote configuration
  // updates.
  TracerConfig& set_remote_configuration_poll_interval(std::chrono::seconds poll_interval, ConfigOrigin origin = ConfigOrigin::CODE);

  // clang-format on

  Expected<FinalizedTracerConfig> finalize();
  Expected<FinalizedTracerConfig> finalize(const Clock& clock);

 private:
  void set_telemetry(StringView name, std::string value, ConfigOrigin origin);

 private:
  TraceSamplerConfig trace_sampler_;
  SpanSamplerConfig span_sampler_;
  DatadogAgentConfig agent_config;
  FinalizedTracerConfig config;

  std::unordered_map<std::string, ConfigTelemetry> telemetry_data_;
};

}  // namespace tracing
}  // namespace datadog
