version: "3.2"
services:

    # The C++ HTTP server to which we added Datadog tracing
    server:
        build:
            context: ./server
            dockerfile: ./Dockerfile
        ports:
            - "127.0.0.1:8000:8000"
        environment:
            # This will override any value of `datadog::tracing::TracerConfig`'s
            # `.agent.url` in `server.cpp`.
            - DD_AGENT_HOST=datadog-agent

    # The Datadog trace agent
    datadog-agent:
        image: datadog/agent
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock:ro'
            - '/proc/:/host/proc/:ro'
            - '/sys/fs/cgroup/:/host/sys/fs/cgroup:ro'
        environment:
            - DD_API_KEY
            - DD_APM_ENABLED=true
            - DD_LOG_LEVEL=ERROR
