version: "3.2"
services:

    server:
        build:
            context: ./server
            dockerfile: ./Dockerfile
        ports:
            - "8000:8000"
        environment:
            - DD_AGENT_HOST=datadog-agent

    datadog-agent:
        image: datadog/agent
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock:ro'
            - '/proc/:/host/proc/:ro'
            - '/sys/fs/cgroup/:/host/sys/fs/cgroup:ro'
        environment:
            - DD_API_KEY
            - DD_APM_ENABLED=true
            - DD_LOG_LEVEL=ERROR
