name: Docker Login Example

on:
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
